# Generated by Django 3.0.6 on 2020-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200611_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialcategory',
            name='catrgory_slug',
        ),
        migrations.AddField(
            model_name='tutorialcategory',
            name='category_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
