# Generated by Django 3.0.6 on 2020-06-11 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200611_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 13, 37, 21, 637309), verbose_name='date published'),
        ),
    ]
